# Generated by Django 5.1.3 on 2024-11-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_file_file_alter_file_name_alter_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, help_text='Имя файла. По умолчанию используется имя загружаемого файла.', max_length=255, null=True),
        ),
    ]
